# Generated by Django 4.2.6 on 2023-11-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_customer_report_task_supportticket_salesopportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm_app.customer",
            ),
        ),
    ]
