# 使用官方的 Python 3.9 镜像作为基础镜像
FROM python:3.9.13-alpine3.16

# 设置工作目录
WORKDIR /app

# 复制应用程序代码到容器中
COPY . /app/

# 安装应用程序的依赖
RUN pip install -r requirements.txt

# 暴露应用程序运行的端口
EXPOSE 8000

# 启动应用程序
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
